services:
  shakthidb:
    build: .
    container_name: shakthidb_service
    environment:
      - POSTGRES_PASSWORD=ShakthiDB@2026
      - POSTGRES_DB=shakthidb
    ports:
      - "15234:5432"
    command: postgres -c shared_buffers=2GB -c work_mem=64MB -c max_connections=200
    volumes:
      - pgdata:/var/lib/postgresql
    restart: always

volumes:
  pgdata:
