import requests
import time

BASE_URL = "http://127.0.0.1:8000"
TIMEOUT = 30

ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin"  # assuming password is same as username unless specified

def test_post_api_audit_upload_with_evidence():
    session = requests.Session()
    try:
        # Step 1: Login as admin to get OTP challenge or direct login
        login_resp = session.post(
            f"{BASE_URL}/api/auth/login",
            json={"username": ADMIN_USERNAME, "password": ADMIN_PASSWORD},
            timeout=TIMEOUT
        )
        assert login_resp.status_code == 200
        login_json = login_resp.json()

        # According to flow, login response can be OTP challenge or direct success.
        # If OTP challenge, verify OTP; else, extract JWT token
        if "otp_required" in login_json and login_json["otp_required"]:
            # Normally, OTP code is generated by TOTP algorithm.
            # For test, assume OTP code can be retrieved or bypassed.
            # Since no direct secret or method is supplied, emulate valid OTP as '123456'
            otp_code = "123456"
            verify_resp = session.post(
                f"{BASE_URL}/api/auth/verify-otp",
                json={"username": ADMIN_USERNAME, "otp_code": otp_code},
                timeout=TIMEOUT
            )
            assert verify_resp.status_code == 200
            token = verify_resp.json().get("token")
        else:
            # If no OTP required, maybe token included directly
            token = login_json.get("token")
            if not token:
                # fallback, throw error for test failed authentication
                raise AssertionError("No token received after login")

        assert token is not None and isinstance(token, str) and len(token) > 0

        headers_auth = {"Authorization": f"Bearer {token}"}

        # Step 2: Create an audit session since we need a valid session_id for upload
        # Minimal session details - creating a dummy session for test
        session_body = {
            "session_name": "Test Upload Session",
            "description": "Session for testing audit upload",
        }
        create_session_resp = session.post(
            f"{BASE_URL}/api/audit/sessions",
            headers=headers_auth,
            json=session_body,
            timeout=TIMEOUT
        )
        assert create_session_resp.status_code == 200
        resp_json = create_session_resp.json()
        session_id = resp_json.get("session_id")
        assert session_id is not None and isinstance(session_id, str) and len(session_id) > 0

        # Step 3: Upload an evidence document
        upload_url = f"{BASE_URL}/api/audit/upload"
        # Prepare a small in-memory file-like object for evidence (e.g. a text file)
        files = {
            "evidence": ("test_evidence.txt", b"Test evidence content", "text/plain"),
        }
        data = {
            "session_id": session_id
        }
        upload_resp = session.post(
            upload_url,
            headers=headers_auth,
            data=data,
            files=files,
            timeout=TIMEOUT
        )
        assert upload_resp.status_code == 200
        upload_json = upload_resp.json()
        # Expecting confirmation or success message
        assert "message" in upload_json or "success" in upload_json or "uploaded" in upload_resp.text.lower()

    finally:
        # Cleanup: delete created audit session if API supports deletion
        # No DELETE endpoint described in PRD, so skip explicit delete
        pass

test_post_api_audit_upload_with_evidence()